name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."
   
    - name: Build and scan image - APP
      uses: dentsusoken/build-and-scan-image@main
      with:
        # Image name and optionally tag in "name:tag" format
        tag: "alexgetup/linuxtips-giropops-senhas:1.0"
    
        # Path to base directory to run `docker build` command (default ".")
        path: "giropops-senhas"
    
        # Path to Dockerfile, which is relative path from "path" parameter (default "Dockerfile")
        dockerfile: Dockerfile
    
        # Enable scanning Dockerfile by hadolint (default "true")
        hadolint-enable: "true"
    
        # Hadolint version.
        hadolint-version: "2.8.0"
    
        # Fail step if rules with a severity above this level are violated (default "info")
        # Acceptable value is one of (error|warning|info|style|ignore|none)
        hadolint-severity: error
    
        # Enable scanning image by dockle (default "true")
        dockle-enable: "false"
    
        # Dockle version.
        dockle-version: "0.4.3"
    
        # Fail step if checkpoints with a severity above this level are violated (default "WARN")
        # Acceptable value is one of (INFO|WARN|FATAL)
        dockle-severity: FATAL
    
        # Enable scanning image by trivy (default "true")
        trivy-enable: "false"
    
        # Trivy version.
        trivy-version: "0.23.0"
    
        # Fail step if image has vulnerabilities with a severity same as this level
        # (default "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL")
        # Acceptable value is comma-separated list of (UNKNOWN|LOW|MEDIUM|HIGH|CRITICAL)
        trivy-severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    
        # Vulnerability types which trivy detect to (default "os,library")
        # Acceptable value is comma-separated list of (os|library)
        trivy-vuln-type: os,library
    
        # Ignore unfixed vulnerabilities (default "false")
        trivy-ignore-unfixed: "false"
    
        # Enable scanning image by snyk (default "false")
        # If enabled, "snyk-token" must be also set.
        snyk-enable: "false"
    
        # Snyk CLI version.
        snyk-version: "1.848.0"
    
        # Snyk API Token (default "")
        # This is necessary if "snyk-enable" is "true".
        snyk-token: ""
    
        # Fail step if image has vulnerabilities with a severity above this level (default "low")
        # Acceptable value is one of (low|medium|high|critical)
        snyk-severity: low
    
        # Exclude base image vulnerabilities (default "false")
        snyk-exclude-base-image-vulns: "false"
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./giropops-senhas/Dockerfile
        push: true
        tags: "alexgetup/linuxtips-giropops-senhas:1.0"             
        
    - name: Build and scan image - REDIS
      uses: dentsusoken/build-and-scan-image@main
      with:
        # Image name and optionally tag in "name:tag" format
        tag: "alexgetup/redis:1.0"
    
        # Path to base directory to run `docker build` command (default ".")
        path: "redis"
    
        # Path to Dockerfile, which is relative path from "path" parameter (default "Dockerfile")
        dockerfile: Dockerfile
    
        # Enable scanning Dockerfile by hadolint (default "true")
        hadolint-enable: "true"
    
        # Hadolint version.
        hadolint-version: "2.8.0"
    
        # Fail step if rules with a severity above this level are violated (default "info")
        # Acceptable value is one of (error|warning|info|style|ignore|none)
        hadolint-severity: error
    
        # Enable scanning image by dockle (default "true")
        dockle-enable: "false"
    
        # Dockle version.
        dockle-version: "0.4.3"
    
        # Fail step if checkpoints with a severity above this level are violated (default "WARN")
        # Acceptable value is one of (INFO|WARN|FATAL)
        dockle-severity: FATAL
    
        # Enable scanning image by trivy (default "true")
        trivy-enable: "false"
    
        # Trivy version.
        trivy-version: "0.23.0"
    
        # Fail step if image has vulnerabilities with a severity same as this level
        # (default "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL")
        # Acceptable value is comma-separated list of (UNKNOWN|LOW|MEDIUM|HIGH|CRITICAL)
        trivy-severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    
        # Vulnerability types which trivy detect to (default "os,library")
        # Acceptable value is comma-separated list of (os|library)
        trivy-vuln-type: os,library
    
        # Ignore unfixed vulnerabilities (default "false")
        trivy-ignore-unfixed: "false"
    
        # Enable scanning image by snyk (default "false")
        # If enabled, "snyk-token" must be also set.
        snyk-enable: "false"
    
        # Snyk CLI version.
        snyk-version: "1.848.0"
    
        # Snyk API Token (default "")
        # This is necessary if "snyk-enable" is "true".
        snyk-token: ""
    
        # Fail step if image has vulnerabilities with a severity above this level (default "low")
        # Acceptable value is one of (low|medium|high|critical)
        snyk-severity: low
    
        # Exclude base image vulnerabilities (default "false")
        snyk-exclude-base-image-vulns: "false"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./redis
        file: ./Dockerfile
        push: true
        tags: "alexgetup/redis:1.0"      
